name: Create release

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        type: string
        description: The version suffix to release
        required: true
    secrets:
      GITHUB_TOKEN:
        required: true
      NUGET_API_KEY:
        required: true

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build solution
        run: dotnet build --configuration Release --framework net6.0
        working-directory: ./src

      - name: Publish MinimalQueues.Core
        run: dotnet publish --configuration Release --framework net6.0 --no-build --no-restore
        working-directory: ./src/MinimalQueues.Core

      - name: Nuget Pack MinimalQueues.Core
        run: dotnet pack --configuration Release --framework net6.0 --no-restore --no-build --version-suffix ${{ inputs.version_suffix }}
        working-directory: ./src/MinimalQueues.Core

      