name: Create release

on:
  workflow_dispatch:
    inputs:
      new_version:
        type: string
        description: The next version to release (SemVer without prefix)
        required: true
    secrets:
      GITHUB_TOKEN:
        required: true
      NUGET_API_KEY:
        required: true

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build solution
        run: dotnet build --no-restore
        working-directory: ./src