name: Test

on:
  workflow_dispatch:  
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::025381531841:role/cztest-mq-role
          aws-region: us-east-2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Run Tests
        run: dotnet test
        working-directory: ./src/tests/MinimalQueues.Tests/Tests
        env:
          ServiceBusNamespace: ${{vars.SERVICEBUSNAMESPACE}}
          ServiceBusTopic: ${{vars.SERVICEBUSTOPIC}}
          ServiceBusSubscription: ${{vars.SERVICEBUSSUBSCRIPTION}}


#https://github.com/aws-actions/configure-aws-credentials
#https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

#https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux